# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('team', models.CharField(max_length=50)),
                ('contract_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
