# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_hitter_pitcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='contract_date',
        ),
    ]
